volumes:
  gymBuddy:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: ${SIGNING_KEY}
      API_KEY: ${API_KEY}
      API_BASE_URL: ${API_BASE_URL}
      DATABASE_URL: postgresql://admin:GymBuddy@db/gymBuddy
      WAIT_HOSTS: db:5432
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: GymBuddy
      POSTGRES_USER: admin
      POSTGRES_DB: gymBuddy
    ports:
      - "15432:5432"
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}

      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
