volumes:
  sculptr:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://sculptr:sculptr@db/sculptr
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  database:
    image: postgres:14.2-bullseye
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - sculptr:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sculptr
      POSTGRES_USER: sculptr
      POSTGRES_DB: sculptr
    ports:
      - 15432:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
